Class = require "lib.class"
STI = require "lib.sti"
Camara = require "lib.camera"
require "jugador"
require "enemigo"
require "enemigos_variantes"
require "estadoJuego"
require "estadoTitulo"
require "maquinaEstado"
require "estadoFin"